#!/bin/sh

# A drop-in replacement for pygments's pygmentize, that talks to the
# pygments server instead.  For right now it only support the
# -O, -f, and -l flags.  You cannot use `,` with -O, use multiple
# -O flags instead.

# You can override this with what port the pygments server is on
: ${PORT:=7878}

url="http://localhost:$PORT/pygmentize?"

while getopts O:f:l:h arg; do
    case $arg in
        O) url="${url}${OPTARG}&";;
        f) url="${url}formatter=${OPTARG}&";;
        l) url="${url}lang=${OPTARG}&";;
        h) echo "USAGE: <man pygmentize>"; exit 0;;
        \?) echo "USAGE: <man pygmentize>"; exit 1;;
    esac
done

# Do some cheap url-escaping.  Luckily, the only thing we need to
# escape in practice is `+`, for languages like `html+jinja`.
url=`echo "$url" | sed 's/\+/%2B/g'`

exec curl -f --data-binary '@-' -H 'Content-type: text/plain' "$url"
